- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Logging in as {{ username }} and password is {{password}}"